### PR TITLE
Implement new/replacement scripts

### PR DESCRIPTION
**Pull request by Juraji**
The implementation of commandCooldown.js needs to be tested, I couldn't since that would severely rek things in my bot...

1. **New command cooldown system**  
Use `!cooldown [command] [seconds]` to set the cooldown for a command (this is always per user)  
Use `!clearcooldown [command]` to clear the cooldown for that command  
Use `$.coolDown.set(command, seconds, perUser)` in your js to set a cooldown, perUser can be true or false  
2. **Implement new bankheist system**  
Use `!heist [points amount]` to start/join a heist during join time  
Use `!heist joinTime [seconds]` to set the duration of the join time  
Use `!heist coolDown [seconds]` to set the minimum time in between heists  
Use `!heist gainPercent [0-100]` to set the percentage to gain on top of the bid  
Use `!heist minBet` to set the minimun entry bid  
Use `!heist maxBet` to set the maximum entry bid  
To add/remove stories see the new lang file
3. **Implement rank system**  
Use `!rank` to view your current rank  
Use `!rank settime` to set the minimum time for a viewer to be in the chat in order to be eligable for a rank (used only to notify viewers)  
Use `!rank set [username] [rank]` to set a viewer's rank, the rank may contain spaces, special characters etc.  
Use `!rank del [username]` to demote a user from their rank  
Use `$.resolveRank(username)` instead of `$.username.resolve()` in your js to resolve the username and add the rank  
This system is NOT automated!

### CODE REVIEW

**Comment by GloriousEggroll** [comment]
Bankheist strings need to be editable and storeable in the database. Reason being this bot also can be/does run as a remote service on some machines, where editing the lang file by hand is not always an option

**Comment by Juraji** [comment]
@GloriousEggroll We've discussed this on discord, in great detail, for dynamic story loading this is the best and cleanest option. But like I also said on discord, I would pull request the code, you guys can fight over merging it or not.

**Comment by GloriousEggroll** [comment]
I do not use discord. I prefer changes to the bot, especially ones pertaining to a script I created, to be presented to me either here or on the forums, in writing. I was not trying to deny your request, as most of your changes are very good. I was just specifying why my original script did not use the lang file, and why most lang file strings also have a database editable option. 

The lang file is meant to be used for default strings, but strings that should have options to be changed need a command to change them, as well as a place to store them. It is a command driven bot, it is very much so not meant for users to have to do anything other than to type a command in order to edit something, as if it were hosted remotely or provided as a remote service of which bot files were not accessible.

**Comment by Juraji** [comment]
@GloriousEggroll Here's the deal, I pushed a new commit to this branch, reverting the old bankheist and adding a new one called adventureSystem.js. So people can choose wich one to use.

**Comment by Juraji** [comment]
Too many bugs/forgotten things, so closing this request before it reks things...

**Pull request closed without merging**
