### PR TITLE
Small fix for issue that was causing the name of a new sub to be the …

### PR DESCRIPTION
**Pull request by scania123**
…same for all subs.

### CODE REVIEW

**Comment by scania123** [comment]
That should not break anything, but I changed it. in #50b31e2

**Comment by GloriousEggroll** [comment]
... you still spelled h-a-n-d-l-e-r wrong

**Comment by scania123** [comment]
OH I thought you were saying 'subscriber' cause the script is called 'subscribe' oops.

**Comment by scania123** [comment]
done in 3d2dd63

**Pull request merged**
